### ISSUE TITLE
YAML syntax doesn't have much contract

### ISSUE THREAD

**Issue by AdrianKoshka** [tobiastimm/raiju#9]
![YAML](https://i.imgur.com/nhj6r07.png)

**Comment by AdrianKoshka** [comment]
I don't know if the quotes are required or not.

**Comment by tobiastimm** [comment]
@AdrianKoshka I've looked into it. Sadly I can't change much about your problem. I could only give the boolean primitives a new color, but that wouldn't help you at all.
